# Generated by Django 5.0.1 on 2025-12-06 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("title", models.CharField(max_length=500)),
                ("author", models.CharField(max_length=300)),
                ("avg_anger", models.FloatField(default=0.0)),
                ("avg_anticipation", models.FloatField(default=0.0)),
                ("avg_disgust", models.FloatField(default=0.0)),
                ("avg_fear", models.FloatField(default=0.0)),
                ("avg_joy", models.FloatField(default=0.0)),
                ("avg_sadness", models.FloatField(default=0.0)),
                ("avg_surprise", models.FloatField(default=0.0)),
                ("avg_trust", models.FloatField(default=0.0)),
                ("avg_valence", models.FloatField(default=0.0)),
                ("avg_arousal", models.FloatField(default=0.0)),
                ("avg_dominance", models.FloatField(default=0.0)),
                ("avg_love", models.FloatField(default=0.0)),
                ("avg_submission", models.FloatField(default=0.0)),
                ("avg_alarm", models.FloatField(default=0.0)),
                ("avg_disappointment", models.FloatField(default=0.0)),
                ("avg_remorse", models.FloatField(default=0.0)),
                ("avg_contempt", models.FloatField(default=0.0)),
                ("avg_aggressiveness", models.FloatField(default=0.0)),
                ("avg_optimism", models.FloatField(default=0.0)),
                ("avg_guilt", models.FloatField(default=0.0)),
                ("avg_curiosity", models.FloatField(default=0.0)),
                ("avg_despair", models.FloatField(default=0.0)),
                ("avg_unbelief", models.FloatField(default=0.0)),
                ("avg_envy", models.FloatField(default=0.0)),
                ("avg_cynicism", models.FloatField(default=0.0)),
                ("avg_pride", models.FloatField(default=0.0)),
                ("avg_hope", models.FloatField(default=0.0)),
                ("avg_anxiety", models.FloatField(default=0.0)),
                ("avg_outrage", models.FloatField(default=0.0)),
                ("num_chunks", models.IntegerField(default=20)),
                ("rising_action_pct", models.FloatField(default=0.0)),
                ("climax_position", models.FloatField(default=0.0)),
                ("resolution_pct", models.FloatField(default=0.0)),
                ("emotional_volatility", models.FloatField(default=0.0)),
                ("primary_genre", models.CharField(blank=True, max_length=100)),
                ("genre_scores", models.JSONField(default=dict)),
                ("topic_summary", models.TextField(blank=True)),
                ("dominant_themes", models.JSONField(default=list)),
                ("emotion_trajectory", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["title"], name="books_book_title_d3218d_idx"),
                    models.Index(
                        fields=["author"], name="books_book_author_b941fe_idx"
                    ),
                    models.Index(
                        fields=["primary_genre"], name="books_book_primary_4fb1cd_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UploadedBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("author", models.CharField(blank=True, max_length=300)),
                ("file", models.FileField(upload_to="uploads/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Analysis"),
                            ("processing", "Processing"),
                            ("completed", "Analysis Complete"),
                            ("failed", "Analysis Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "analyzed_book",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_source",
                        to="books.book",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
