# Generated by Django 5.0.1 on 2025-12-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="bookshelves",
            field=models.JSONField(default=list),
        ),
    ]
